# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

HARDataCreationC <- function(vRealizedmeasure, vLags) {
    .Call(`_HARModel_HARDataCreationC`, vRealizedmeasure, vLags)
}

HarForecastLoopingC <- function(vRealizedmeasure, vLags, vCoef, iNRoll, iNAhead, j) {
    .Call(`_HARModel_HarForecastLoopingC`, vRealizedmeasure, vLags, vCoef, iNRoll, iNAhead, j)
}

rcpparma_hello_world <- function() {
    .Call(`_HARModel_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_HARModel_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_HARModel_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_HARModel_rcpparma_bothproducts`, x)
}

