// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// HARDataCreationC
NumericMatrix HARDataCreationC(NumericVector vRealizedmeasure, arma::vec vLags);
RcppExport SEXP _HARModel_HARDataCreationC(SEXP vRealizedmeasureSEXP, SEXP vLagsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vRealizedmeasure(vRealizedmeasureSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type vLags(vLagsSEXP);
    rcpp_result_gen = Rcpp::wrap(HARDataCreationC(vRealizedmeasure, vLags));
    return rcpp_result_gen;
END_RCPP
}
// HarForecastLoopingC
NumericVector HarForecastLoopingC(NumericVector vRealizedmeasure, NumericVector vLags, NumericVector vCoef, int iNRoll, int iNAhead, int j);
RcppExport SEXP _HARModel_HarForecastLoopingC(SEXP vRealizedmeasureSEXP, SEXP vLagsSEXP, SEXP vCoefSEXP, SEXP iNRollSEXP, SEXP iNAheadSEXP, SEXP jSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vRealizedmeasure(vRealizedmeasureSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vLags(vLagsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vCoef(vCoefSEXP);
    Rcpp::traits::input_parameter< int >::type iNRoll(iNRollSEXP);
    Rcpp::traits::input_parameter< int >::type iNAhead(iNAheadSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    rcpp_result_gen = Rcpp::wrap(HarForecastLoopingC(vRealizedmeasure, vLags, vCoef, iNRoll, iNAhead, j));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_hello_world
arma::mat rcpparma_hello_world();
RcppExport SEXP _HARModel_rcpparma_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpparma_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_outerproduct
arma::mat rcpparma_outerproduct(const arma::colvec& x);
RcppExport SEXP _HARModel_rcpparma_outerproduct(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_outerproduct(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_innerproduct
double rcpparma_innerproduct(const arma::colvec& x);
RcppExport SEXP _HARModel_rcpparma_innerproduct(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_innerproduct(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_bothproducts
Rcpp::List rcpparma_bothproducts(const arma::colvec& x);
RcppExport SEXP _HARModel_rcpparma_bothproducts(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_bothproducts(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_HARModel_HARDataCreationC", (DL_FUNC) &_HARModel_HARDataCreationC, 2},
    {"_HARModel_HarForecastLoopingC", (DL_FUNC) &_HARModel_HarForecastLoopingC, 6},
    {"_HARModel_rcpparma_hello_world", (DL_FUNC) &_HARModel_rcpparma_hello_world, 0},
    {"_HARModel_rcpparma_outerproduct", (DL_FUNC) &_HARModel_rcpparma_outerproduct, 1},
    {"_HARModel_rcpparma_innerproduct", (DL_FUNC) &_HARModel_rcpparma_innerproduct, 1},
    {"_HARModel_rcpparma_bothproducts", (DL_FUNC) &_HARModel_rcpparma_bothproducts, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_HARModel(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
