// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// HARDataCreationC
NumericMatrix HARDataCreationC(NumericVector vRealizedmeasure, NumericVector vLags);
RcppExport SEXP _HARModel_HARDataCreationC(SEXP vRealizedmeasureSEXP, SEXP vLagsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vRealizedmeasure(vRealizedmeasureSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vLags(vLagsSEXP);
    rcpp_result_gen = Rcpp::wrap(HARDataCreationC(vRealizedmeasure, vLags));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_HARModel_HARDataCreationC", (DL_FUNC) &_HARModel_HARDataCreationC, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_HARModel(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
