// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// HARDataCreationC
NumericMatrix HARDataCreationC(NumericVector vRealizedmeasure, arma::vec vLags);
RcppExport SEXP _HARModel_HARDataCreationC(SEXP vRealizedmeasureSEXP, SEXP vLagsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vRealizedmeasure(vRealizedmeasureSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type vLags(vLagsSEXP);
    rcpp_result_gen = Rcpp::wrap(HARDataCreationC(vRealizedmeasure, vLags));
    return rcpp_result_gen;
END_RCPP
}
// HarForecastLoopingC
NumericVector HarForecastLoopingC(NumericVector vRealizedmeasure, NumericVector vLags, NumericVector vCoef, int iNRoll, int iNAhead, int j);
RcppExport SEXP _HARModel_HarForecastLoopingC(SEXP vRealizedmeasureSEXP, SEXP vLagsSEXP, SEXP vCoefSEXP, SEXP iNRollSEXP, SEXP iNAheadSEXP, SEXP jSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vRealizedmeasure(vRealizedmeasureSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vLags(vLagsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vCoef(vCoefSEXP);
    Rcpp::traits::input_parameter< int >::type iNRoll(iNRollSEXP);
    Rcpp::traits::input_parameter< int >::type iNAhead(iNAheadSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    rcpp_result_gen = Rcpp::wrap(HarForecastLoopingC(vRealizedmeasure, vLags, vCoef, iNRoll, iNAhead, j));
    return rcpp_result_gen;
END_RCPP
}
// RVsim
NumericVector RVsim(int iTradesPerSamplingPeriod, int iAggregationPeriods, double dMu, double dSigma2);
RcppExport SEXP _HARModel_RVsim(SEXP iTradesPerSamplingPeriodSEXP, SEXP iAggregationPeriodsSEXP, SEXP dMuSEXP, SEXP dSigma2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type iTradesPerSamplingPeriod(iTradesPerSamplingPeriodSEXP);
    Rcpp::traits::input_parameter< int >::type iAggregationPeriods(iAggregationPeriodsSEXP);
    Rcpp::traits::input_parameter< double >::type dMu(dMuSEXP);
    Rcpp::traits::input_parameter< double >::type dSigma2(dSigma2SEXP);
    rcpp_result_gen = Rcpp::wrap(RVsim(iTradesPerSamplingPeriod, iAggregationPeriods, dMu, dSigma2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_HARModel_HARDataCreationC", (DL_FUNC) &_HARModel_HARDataCreationC, 2},
    {"_HARModel_HarForecastLoopingC", (DL_FUNC) &_HARModel_HarForecastLoopingC, 6},
    {"_HARModel_RVsim", (DL_FUNC) &_HARModel_RVsim, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_HARModel(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
