# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

HARDataCreationC <- function(vRealizedMeasure, vLags) {
    .Call(`_HARModel_HARDataCreationC`, vRealizedMeasure, vLags)
}

HARSimC <- function(iLength, vLags, dConst, coef, dSigma) {
    .Call(`_HARModel_HARSimC`, iLength, vLags, dConst, coef, dSigma)
}

fastLMcoef <- function(X, y) {
    .Call(`_HARModel_fastLMcoef`, X, y)
}

