# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

HARDataCreationC <- function(vRealizedMeasure, vPeriods, h = 1L) {
    .Call(`_HARModel_HARDataCreationC`, vRealizedMeasure, vPeriods, h)
}

HARMatCombine <- function(mA, mB) {
    .Call(`_HARModel_HARMatCombine`, mA, mB)
}

HARSimC <- function(iLength, vLags, dConst, coef, dSigma) {
    .Call(`_HARModel_HARSimC`, iLength, vLags, dConst, coef, dSigma)
}

fastLMcoef <- function(X, y) {
    .Call(`_HARModel_fastLMcoef`, X, y)
}

