# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

HARDataCreationC <- function(vRealizedmeasure, vLags) {
    .Call(`_HARModel_HARDataCreationC`, vRealizedmeasure, vLags)
}

HarForecastLoopingC <- function(vRealizedmeasure, vLags, vCoef, iNRoll, iNAhead, j) {
    .Call(`_HARModel_HarForecastLoopingC`, vRealizedmeasure, vLags, vCoef, iNRoll, iNAhead, j)
}

RVsim <- function(iTradesPerSamplingPeriod, iAggregationPeriods, dMu, dSigma2) {
    .Call(`_HARModel_RVsim`, iTradesPerSamplingPeriod, iAggregationPeriods, dMu, dSigma2)
}

